### ISSUE TITLE
New Method of updating

### ISSUE THREAD

**Issue by TheCrimsonDevil** [Arks-Layer/PSO2Tweaker#21]
Why does it only work for like 90% of people? Let's find out and fix it. Can I get some volunteers who have issues with it?

**Comment by AyumiMitsuki** [comment]
Me, I got that issue from using the new method, file check founds 900+ missing files, and I idky

**Comment by ryanelian** [comment]
I saw this issue yesterday and decided to refactor out and remake the Tweaker update system.

![updater](https://cloud.githubusercontent.com/assets/8892187/16903087/0149cfae-4c9e-11e6-9267-aeae5f812694.PNG)

It is now build to utilize async and parallel TPL from ground-up. Fully managed code, including the MD5 provider (Now built-in `System.Security.Cryptography` and performs MD5 hashing on-the-fly as file streams are being read). Very performant and highly optimized. 

Apparently quite accurate too, as I am able to update the game files using this library and then launch the game without issues (so far).

![updater2](https://cloud.githubusercontent.com/assets/8892187/16903100/3fb32a74-4c9e-11e6-939c-ae857845b146.PNG)

![updater3](https://cloud.githubusercontent.com/assets/8892187/16903102/42830bca-4c9e-11e6-938d-f47aaeba9d31.PNG)

Notice how it kicks off online downloads in parallel and queue them automatically to maximize user bandwidth, using TPL hill-climbing to optimize throughput.

The new update module has also consolidated old + new patching method. Solves the following update scenarios:

1. User decided to do full rescan of game hashes. The next time update happens, all hashes were already generated and game will only perform delta download. I don't think this is the current case with existing update system.

2. Hash missing. Triggers full rescan just to be safe. Just like current Tweaker.

3. Delta updates in-between patches. Last update patches will be treated as latest files instead of maintaining hashes manually, in order to stay sane with SEGA's update stuffs.

-----

Now that's the good news, I have the bad news:

1. All these features are build upon .NET 4.5. I mean, .NET 4.0 (current Tweaker framework) was released in 2010 and .NET 4.5 was released in 2012. Surely it's time for an upgrade, no? (Might as well go straight to 4.6.1, for justice)

2. Between the 3800+ lines of FrmMain.vb spaghetti codes and the fact that Tweaker uses proprietary UI framework instead of traditional ones like Windows Form, I am unable to integrate this into the Tweaker for plug-and-play trial. I might just make a separate Windows Form project just to demo this to public.

3. This library uses async-await heavily for tasks that require promises, such as downloading a file. Apparently Tweaker is still lacking in that department and future integration will require special efforts in this area.

4. I haven't baked the backup-restore and EN-patch features into the library.

**Comment by TheCrimsonDevil** [comment]
@ryanelian That's AMAZING! \ o / Excellent work! This is definitely an area we needed to improve upon, and it seems like you've done a wonderful job of it :D

For the bad news:

1) No issue here - I had simply select 4.0 upon creation. I have no issues going to 4.5 (or 4.6.1).

2) If you design the code, I can worry about making sure it's inserted into the (horrible) spaghetti code. I can also grab you the proprietary UI file, of course.

3) Nothing ever easy is worthwhile - I look forward to the challenges like this.

4) No worries - Those aren't *really* even part of the update system - It's just a matter of copying and backing up the files pre-EN install, and for uninstalling them, downloading the files that the patch uses from SEGA.

Let me know what you need and when I can start playing with it :3

**Comment by ryanelian** [comment]
Right now I'm swamped with IRL stuffs. This was just something I cooked up during Sunday. I want to implement these features before letting you play with it:

- At least a backup restore feature before fetching the game client hashes. For now, the backup tooling is indiscriminate and indifferent to which backup types and will simply restore everything in `\data\win32\backup` folder.

- Versioning stuffs. I noticed that Tweaker is pulling `http://arks-layer.com/vanila/version.txt` to `%USERPROFILE%\Documents\SEGA\PHANTASYSTARONLINE2\version.ver` but I haven't actually coded this in, because...

- I'm also wondering, what's the difference between `http://arks-layer.com/vanila/version.txt` and `gameversion.ver` that SEGA provides. I mean, the numbers are obviously different `4.0302.0` vs `v40300_rc_109`. But why not rely on SEGA's?

- I actually wondering why currently Tweaker makes special efforts to download `pso2launcher.exe`, `pso2updater.exe`, `pso2.exe` instead of relying on the hashes provided by the patchlist. Those exes actually exists in the patchlist, so surely you don't need to explicitly download them everytime unless they have changed, no?

- Censor removal and backup built-in into the update process. Apparently it's just deleting `data/win32/ffbff2ac5b7a7948961212cefd4d402c` so should be easy to implement.

- Resume patching if interrupted. I haven't actually think of how to deal with this.

These might be finished in a week (or two) if my IRL stuffs don't get hectic. I don't know.
(╯° °）╯︵ ┻━┻)

---------------

Replying above your latest post.

1 & 3. Sweet.

2. Nah I'm good without the UI framework. I feel that if I touch the Tweaker source, I'll awaken some Flying Cthulhu Spaghetti Monster abomination and will lose sleep. Anyways, you can later implement interfaces to interact with Tweaker UI like IRenderer.

![irenderer](https://cloud.githubusercontent.com/assets/8892187/16909399/b684aaac-4cfc-11e6-8a3b-144fd56ca989.PNG)

I'd imagine that in current Tweaker, `WriteLine` will just write to that little text windows on the bottom-left side. Similarly, `ParseProgress` can be implemented into existing progress bar stuff.

However, the `UpdateDownloadProgress` is a different beast. Since now patch files can be downloaded in parallel using the download manager, like an actual download manager, I don't think one progress bar is enough. :sweat_smile:

**Comment by flyergo** [comment]
Just saw this post a few minutes ago.

A few months ago, while browsing the spagetti code, I saw that the Tweaker could maybe need a speed-up in the download process by adding a multitask-based download queue using TPL and excluding user-selected patch files from the patches.

Based on that idea I built a small prototype for testing that used a 300+ Mbit/s server to see how much I would gain by refactoring it and tried to optimize it the best I could. 

I also ran into some of the problems you encountered like .NET Framework version, gameversion.ver and possible refactoring/changing the whole download process (or at least most of it).

Then some more urgent projects came up and my ISP decided to fuck up my whole network (I blame my router), so I forgot about all this.

Nevertheless: I am still interested in improving the download time by optimizing it. 

Since I am currently at work and merely skimmed through the posts: I will take a look at some of the points later and maybe I can provide you some answers, information or help.

PS: I bump most of your suggestions/decisions, like pre-evaluating patches and exe-hashes, TPL (asnyc & await) and nuget/Zlib. And if it was me I wouldn't even bother giving the user the option to remove the censor file... just don't even download it for all tweaker users.

**Comment by TheCrimsonDevil** [comment]
>I'm also wondering, what's the difference between http://arks-layer.com/vanila/version.txt and gameversion.ver that SEGA provides. I mean, the numbers are obviously different 4.0302.0 vs v40300_rc_109. But why not rely on SEGA's?

This is how the Tweaker detects updates - Arks-Layer downloads SEGA's version file every hour, and mirrors it. Tweaker checks that file against it's local copy, and if they're different, executes an update. I don't recall why I switched to this method, as it was so long ago, but I *think* SEGA's servers sometimes failed to serve the file correctly, resulting in outdated clients. We can switch back to SEGA's (as long as it works reliably ofc)

>I actually wondering why currently Tweaker makes special efforts to download pso2launcher.exe, pso2updater.exe, pso2.exe instead of relying on the hashes provided by the patchlist. Those exes actually exists in the patchlist, so surely you don't need to explicitly download them everytime unless they have changed, no?

Again, I don't recall the reasoning for this, but I'm sure there was a reason before. It can certainly be thrown into the normal process, though.

>Prepatch mechanism. This is another can of worms that sooner or later needs to be dealt with, as prepatches change game client files without using the weekly patchlist (hence requiring the Tweaker to inject the latest game client hashes with prepatch hashes).

This feature is literally the bane of my existence, ugh.

>1) Sweet.

The latest update upgraded the .NET framework to 4.5, so it's live and out in the wild. This way, we can make sure everyone is ready later.

>2) Nah I'm good without the UI framework. I feel that if I touch the Tweaker source, I'll awaken some Flying Cthulhu Spaghetti Monster abomination and will lose sleep. Anyways, you can later implement interfaces to interact with Tweaker UI like IRenderer.

Yeah, I know that feeling. And okay!

>However, the UpdateDownloadProgress is a different beast. Since now patch files can be downloaded in parallel using the download manager, like an actual download manager, I don't think one progress bar is enough. :sweat_smile:

Haha, yeah. I'll definitely have to make some UI changes, which is something I've been looking at doing anyhow.

>4) Yes but in the future I want to tackle the part about the 7zip dependency. Currently 7za.exe is shipped along with the Tweaker for whatever reason it might be needed. (My educated guess is that it's being used for applying EN patches). However, LZMA SDK is available for .NET https://www.nuget.org/packages/Zlib.Portable/
Wouldn't it be wonderful if the unzipping module is also fully-managed within the Tweaker? :smile:

You are correct! And oooooh, I'll go ahead and integrate that. :D

>And if it was me I wouldn't even bother giving the user the option to remove the censor file... just don't even download it for all tweaker users.

Another thing I may implement ASAP, but should definitely be done at some point.

**Comment by ryanelian** [comment]
Ahem, just a status update, since 13 days have passed since last time I posted here.

I haven't touched the code a single line due to:

1. Instead of dying down, my IRL project is getting even more hectic due to the development team edging closer to the deadlines and we need to be set for deployment soon.

2. Campus stuffs. End of semester reports are the worst.

3. Girlfriend coming back from the job site outside town (after 2 months being deployed), will be staying here for a week before she gets deployed again.

As soon as those stuffs are sorted out and I have room for breathing, I'll work on the codes again, I promise. :sweat_smile:

**Comment by flyergo** [comment]
> FYI, `gameversion.ver` gets updated from `4.0302.0` to `4.0302.1` so I'm quite sure that you can use SEGA's to keep track of the update, which I will incorporate to my library. but because I'm feeling lazy, I'll leave the versioning to you.

I think I remember some updates on which SEGA didn't change the `gameversion.ver`, but the official launcher still triggered an update. 

I noticed the official launcher downloads the `version.ver` on startup, which currently contains `v40300_rc_122`.

![FiddlerScreenshot](https://cloud.githubusercontent.com/assets/10029199/17397059/a1366f40-5a36-11e6-9f5c-347debc923bb.PNG)
...after that an update was triggered without even downloading the `gameversion.ver`.
(Not sure why they download the `launcherlist.txt` twice)

So I assume they use the `version.ver` and not `gameversion.ver` to trigger updates in general and `gameversion.ver` might serve another purpose.

Anyway, this needs more investigation to make it work like the official launcher.

**Comment by TheCrimsonDevil** [comment]
Good work everyone! \ o /

**Comment by belldandu** [comment]
Sweet

**Comment by ryanelian** [comment]
So it didn't actually burn people's computer?

I'm amazed.

Great job everyone :wine_glass: :tada:

**Comment by flyergo** [comment]
@ryanelian I noticed during todays update, that the number of parallel downloads is limited to `2`. 
Is this an expected behaviour?

Setting [`System.Net.ServicePointManager.DefaultConnectionLimit`](https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.defaultconnectionlimit.aspx) higher at start could increase the number of parallel downloads, which could improve the downloadrate for a lot of small files, since the default value `2` still causes connection drops.

**Comment by ryanelian** [comment]
> @ryanelian I noticed during todays update, that the number of parallel downloads is limited to 2.
Is this an expected behaviour?

> Setting System.Net.ServicePointManager.DefaultConnectionLimit higher at start could increase the number of parallel downloads, which could improve the downloadrate for a lot of small files, since the default value 2 still causes connection drops.


I did not set the maximum parallel download and left the job of orchestrating the downloads to the task manager.

If based TPL task manager decided that 2 is the way to go, then 2 it is. I've sworn I've seen more than 2 downloads occurring at times, and then there's some cases where it actually limits the download down to 1 concurrency because it thinks that 1 is enough.

Although, Tweaker can independently set that value regardless of the engine settings, if the community wishes it.

**Comment by flyergo** [comment]
> TPL God

haha

> If the based TPL God decided that 2 is the way to go, then 2 it is. I've sworn I've seen more than 4 downloads occurring at times, and then there's some cases where it actually limits the download down to 1 concurrency because it thinks that doing more than 1 is bad.

As from what I've seen so far everyone seems to have only 2, since that is the number of active `WebClient`s.

> Although, Tweaker can independently set that value regardless of the engine settings, if the community wishes it.

I don't know best practice for this myself, unfortuneatly. But searching for that on Github, there doesn't seem to be a right way to go either. I've seen people set it to `8`, `10`, `24`, `32` or even `Int32.MaxValue`.

@ryanelian, @TheCrimsonDevil  Would suggest to set it to `8` or `10` for now.
